// lib/utils/validators/screening/person/regex.js
  export const defaultValue = {
    hn: null, hn_index: null, prefix_id: null, prefix_id_en: null, firstname: null, firstname_en: null, 
    lastname: null, lastname_en: null, idcard: null, passport: null, sex_id: null, 
    unknow_birthday: null, birthday: null, age: null, bloodgroup_id: null, nationalities_id: null, 
    ethnicities_id: null, tel: null, occupation_id: null, occupations_other:null, organization_id: null, healthcare_right_id:null,
    main_hospital:null, secondary_hospital:null, important_information:null,
    type: null, 
    houseno: null, 
    villagenno: null, 
    road: null, 
    province_id: null, 
    district_id: null, 
    subdistrict_id: null, 
    zip_code: null, 
  };
  
  export const regex = {

    nameTh: /^[\p{Script=Thai}\s]+$/u,
    nameEn: /^[A-Za-z\s]+$/,
    
    firstnamethen: /^[\p{Script=Thai}a-zA-Z\s]+$/u,
    lastnamethen: /^[\p{Script=Thai}a-zA-Z\s]+$/u,

    hn: /^[0-9]+$/,
    hn_index: /^[0-9A-Za-z]+$/,
    prefix_id: /^[0-9]+$/,
    firstname: /^[\p{Script=Thai}]+$/u,
    lastname: /^[\p{Script=Thai}]+$/u,
    prefix_id_en: /^[0-9]+$/,
    firstname_en: /^[A-Za-z]+$/,
    lastname_en: /^[A-Za-z]+$/,
    idcard: /^[0-9A-Za-z-]+$/,
    passport: /^[0-9A-Za-z-]+$/,
    sex_id: /^[0-9]+$/,
    birthday: /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/,
    unknow_birthday: /^[0-1]+$/,
    age: /^[0-9]+$/,
    bloodgroup_id: /^[0-9]+$/,
    nationalities_id: /^[0-9]+$/,
    ethnicities_id: /^[0-9]+$/,
    tel: /^[0-9-+]+$/,
    occupation_id: /^[0-9]+$/,
    occupations_other: /^(?:[\p{Script=Thai}a-zA-Z0-9\s./-])+$/u,
    organization_id: /^[0-9]+$/,
    healthcare_right_id: /^[0-9]+$/,
    main_hospital: /^[\p{Script=Thai}a-zA-Z0-9\s.*\/=(),?!@#\$%\^&_\+\-:;'"[\]{}<>]+$/u,
    secondary_hospital: /^[\p{Script=Thai}a-zA-Z0-9\s.*\/=(),?!@#\$%\^&_\+\-:;'"[\]{}<>]+$/u,
    important_information: /^(?:[\p{Script=Thai}a-zA-Z0-9\s./-])+$/u,
    houseno: /^(?:[\p{Script=Thai}a-zA-Z0-9\s./-])+$/u,
    villagenno: /^(?:[\p{Script=Thai}a-zA-Z0-9\s./-])+$/u,
    road: /^(?:[\p{Script=Thai}a-zA-Z0-9\s./-])+$/u,
    province_id: /^[0-9]+$/,
    district_id: /^[0-9]+$/,
    subdistrict_id: /^[0-9]+$/,
    zip_code: /^[0-9]+$/,

  };

  export const replacePattern = {

    nameTh:  /[^\p{Script=Thai}\s]/gu,
    nameEn: /[^A-Za-z\s]/g,

    firstnamethen:  /[^\p{Script=Thai}a-zA-Z\s]/gu,
    lastnamethen:  /[^\p{Script=Thai}a-zA-Z\s]/gu,
  
    hn: /[^0-9]/g,
    hn_index: /[^0-9A-Za-z]/g,
    prefix_id: /[^0-9]/g,
    firstname: /[^\p{Script=Thai}]/gu,
    lastname: /[^\p{Script=Thai}]/gu,
    prefix_id_en: /[^0-9]/g,
    firstname_en: /[^A-Za-z]/g,
    lastname_en: /[^A-Za-z]/g,
    idcard: /[^0-9A-Za-z-]/g,
    passport: /[^0-9A-Za-z-]/g,
    sex_id: /[^0-9]/g,
    birthday: /[^0-9\-]/g, // yyyy-mm-dd รูปแบบตัวเลขและ -
    unknow_birthday: /[^0-1]/g,
    age: /[^0-9]/g,
    bloodgroup_id: /[^0-9]/g,
    nationalities_id: /[^0-9]/g,
    ethnicities_id: /[^0-9]/g,
    tel: /[^0-9\-\+]/g,
    occupation_id: /[^0-9]/g,
    occupations_other: /[^\p{Script=Thai}a-zA-Z0-9\s./-]/gu,
    organization_id: /[^0-9]/g,
    healthcare_right_id: /[^0-9]/g,
    main_hospital: /[^\p{Script=Thai}a-zA-Z0-9\s.*\/=(),?!@#\$%\^&_\+\-:;'"[\]{}<>]/gu,
    secondary_hospital: /[^\p{Script=Thai}a-zA-Z0-9\s.*\/=(),?!@#\$%\^&_\+\-:;'"[\]{}<>]/gu,
    important_information: /[^\p{Script=Thai}a-zA-Z0-9\s./-]/gu,
    houseno: /[^\p{Script=Thai}a-zA-Z0-9\s./-]/gu,
    villagenno: /[^\p{Script=Thai}a-zA-Z0-9\s./-]/gu,
    road: /[^\p{Script=Thai}a-zA-Z0-9\s./-]/gu,
    province_id: /[^0-9]/g,
    district_id: /[^0-9]/g,
    subdistrict_id: /[^0-9]/g,
    zip_code: /[^0-9]/g,
  };
  
  export const regexMessage = {
    type: {

      nameTh: "ประเภทข้อมูล ชื่อ-นามสกุล (ไทย) ไม่ถูกต้อง",
      nameEn: "ประเภทข้อมูล ชื่อ-นามสกุล (Eng) ไม่ถูกต้อง",
    
      firstnamethen: "ประเภทข้อมูล ชื่อ (ไทย - Eng) ไม่ถูกต้อง",
      lastnamethen: "ประเภทข้อมูล นามสกุล (ไทย - Eng) ไม่ถูกต้อง",

      hn: "ประเภทข้อมูล HN ไม่ถูกต้อง",
      hn_index: "ประเภทข้อมูล HN ไม่ถูกต้อง",
      prefix_id: "ประเภทข้อมูล คำนำหน้าชื่อ (ไทย) ไม่ถูกต้อง",
      firstname: "ประเภทข้อมูล ชื่อจริง (ไทย) ไม่ถูกต้อง",
      lastname: "ประเภทข้อมูล นามสกุล (ไทย) ไม่ถูกต้อง",
      thaiengFirstname: "ประเภทข้อมูล ชื่อจริง ไม่ถูกต้อง",
      thaiengLastname: "ประเภทข้อมูล ชื่อจริง ไม่ถูกต้อง",
      prefix_id_en: "ประเภทข้อมูล คำนำหน้าชื่อ (Eng) ไม่ถูกต้อง",
      firstname_en: "ประเภทข้อมูล ชื่อจริง (Eng) ไม่ถูกต้อง",
      lastname_en: "ประเภทข้อมูล นามสกุล (Eng) ไม่ถูกต้อง",
      idcard: "ประเภทข้อมูล เลขบัตรประชาชน ไม่ถูกต้อง",
      passport: "ประเภทข้อมูล พาสปอร์ต ไม่ถูกต้อง",
      sex_id: "ประเภทข้อมูล เพศ ไม่ถูกต้อง",
      birthday: "ประเภทข้อมูล วันเกิด ไม่ถูกต้อง",
      unknow_birthday: "ประเภทข้อมูล ไม่ทราบวันเกิด ไม่ถูกต้อง",
      age: "ประเภทข้อมูล อายุ ไม่ถูกต้อง",
      bloodgroup_id: "ประเภทข้อมูล กรุ๊ปเลือก ไม่ถูกต้อง",
      nationalities_id: "ประเภทข้อมูล สัญชาติ ไม่ถูกต้อง",
      ethnicities_id: "ประเภทข้อมูล เชื้อชาติ ไม่ถูกต้อง",
      tel: "ประเภทข้อมูล หมายเลขโทรศัพท์ ไม่ถูกต้อง",
      occupation_id: "ประเภทข้อมูล อาชีพ ไม่ถูกต้อง",
      occupations_other: "ประเภทข้อมูล อาชีพอื่นๆ ไม่ถูกต้อง",
      organization_id: "ประเภทข้อมูล หน่วยงาน ไม่ถูกต้อง",
      healthcare_right_id: "ประเภทข้อมูล ID สิทธ์การรักษา ไม่ถูกต้อง",
      main_hospital: "ประเภทข้อมูล โรงพยาบาลหลัก ไม่ถูกต้อง",
      secondary_hospital: "ประเภทข้อมูล โรงพยาบาลรอง ไม่ถูกต้อง",
      important_information: "ประเภทข้อมูล ข้อมูลสำคัญ ไม่ถูกต้อง",
      houseno: "ประเภทข้อมูล บ้านเลขที่ ไม่ถูกต้อง",
      villagenno: "ประเภทข้อมูล หมู่บ้าน ไม่ถูกต้อง",
      road: "ประเภทข้อมูล ถนน ไม่ถูกต้อง",
      province_id: "ประเภทข้อมูล จังหวัด ไม่ถูกต้อง",
      district_id: "ประเภทข้อมูล อำเภอ ไม่ถูกต้อง",
      subdistrict_id: "ประเภทข้อมูล ตำบล ไม่ถูกต้อง",
      zip_code: "ประเภทข้อมูล รหัสไปรษณีย์ ไม่ถูกต้อง",
    },
    format: {

      nameTh: "ชื่อ-นามสกุล (ไทย) ต้องเป็นตัวอักษรภาษาไทย เท่านั้น",
      nameEn: "ชื่อ-นามสกุล (Eng) ต้องเป็นตัวอักษรภาษาอังกฤษ เท่านั้น",

      firstnamethen: "ชื่อ (ไทย - Eng) ต้องเป็นตัวอักษรภาษาไทยหรืออังกฤษ เท่านั้น",
      lastnamethen: "นามสกุล (ไทย - Eng) ต้องเป็นตัวอักษรภาษาไทยหรืออังกฤษ เท่านั้น",

      hn_index: "HN ต้องเป็นตัวเลข เท่านั้น หรือตัวอักษรเท่านั้นเช่น HNxxxx",
      hn: "HN ต้องเป็นตัวเลข เท่านั้น",
      prefix_id: "ID คำนำหน้าชื่อ (ไทย) ต้องเป็นตัวเลข เท่านั้น",
      firstname: "ชื่อจริง (ไทย) ต้องเป็นตัวอักษรภาษาไทย เท่านั้น ห้ามมีเว้นวรรค",
      lastname: "นามสกุล (ไทย) ต้องเป็นตัวอักษรภาษาไทย เท่านั้น ห้ามมีเว้นวรรค",
      prefix_id_en: "ID คำนำหน้าชื่อ (Eng) ต้องเป็นตัวเลข เท่านั้น",
      firstname_en: "ชื่อจริง (Eng) ต้องเป็นตัวอักษรภาษาไทย เท่านั้น ห้ามมีเว้นวรรค",
      lastname_en: "นามสกุล (Eng) ต้องเป็นตัวอักษรภาษาไทย เท่านั้น ห้ามมีเว้นวรรค",
      thaiengFirstName: "ชื่อจริง ต้องเป็นตัวอักษรภาษาไทยหรืออังกฤษ เท่านั้น",
      thaiengLastname: "นามสกุล ต้องเป็นตัวอักษรภาษาไทยหรืออังกฤษ เท่านั้น",
      idcard: "เลขบัตรประชาชน ต้องเป็นตัวเลขหรืออังกฤษ อนุญาติให้มี - ได้ เท่านั้น",
      passport: "พาสปอร์ต ต้องเป็นตัวเลขหรือตัวอักษรอังกฤษ อนุญาติให้มี - ได้ เท่านั้น",
      sex_id: "ID เพศ ต้องเป็นตัวเลข เท่านั้น",
      birthday: "วัน-เดือน-ปีเกิด ต้องเป็นรูปแบบ YYYY-mm-dd เท่านั้น",
      unknow_birthday: "ข้อมูลไม่ทราบวันเกิดต้องเป็น 0 หรือ 1 เท่านั้น",
      age: "ข้อมูลอายุต้องเป็นตัวเลข เท่านั้น",
      bloodgroup_id: "ID กรุ๊ปเลือก ต้องเป็นตัวเลข เท่านั้น",
      nationalities_id: "ID สัญชาติ ต้องเป็นตัวเลข เท่านั้น",
      ethnicities_id: "ID เชื้อชาติ ต้องเป็นตัวเลข เท่านั้น",
      tel: "หมายเลขโทรศัพท์ อนุญาติให้กรอก ตัวเลข,-,+ ได้ เท่านั้น",
      occupation_id: "ID อาชีพ ต้องเป็นตัวเลข เท่านั้น",
      occupations_other: "อาชีพอื่นๆ ต้องเป็นตัวอักษรภาษาไทยหรืออังกฤษ และ อนุญาติให้กรอกตัวเลข, -, ., /, เว้นวรรค ได้ เท่านั้น",
      organization_id: "ID หน่วยงาน ต้องเป็นตัวเลข เท่านั้น",
      healthcare_right_id: "ID สิทธ์การรักษา ต้องเป็นตัวเลข เท่านั้น",
      main_hospital: "โรงพยาบาลหลัก ต้องเป็นตัวอักษรภาษาไทยหรืออังกฤษ และ อนุญาติให้กรอกตัวเลข, -, ., /, เว้นวรรค ได้ เท่านั้น",
      secondary_hospital: "โรงพยาบาลรอง ต้องเป็นตัวอักษรภาษาไทยหรืออังกฤษ และ อนุญาติให้กรอกตัวเลข, -, ., /, เว้นวรรค ได้ เท่านั้น",
      important_information: "ข้อมูลสำคัญ ต้องเป็นตัวอักษรภาษาไทยหรืออังกฤษ และ อนุญาติให้กรอกตัวเลข, -, ., /, เว้นวรรค ได้ เท่านั้น",
      houseno: "บ้านเลขที่ ต้องห้ามมีสัญลักษณ์พิเศษ อนุญาติให้กรอก เว้นวรรค, ., -, / ได้ เท่านั้น",
      villagenno: "หมู่บ้าน ต้องห้ามมีสัญลักษณ์พิเศษ อนุญาติให้กรอก เว้นวรรค, ., -, / ได้ เท่านั้น",
      road: "ถนน ต้องห้ามมีสัญลักษณ์พิเศษ อนุญาติให้กรอก เว้นวรรค, ., -, / ได้ เท่านั้น",
      province_id: "ID จังหวัด ต้องเป็นตัวเลข เท่านั้น",
      district_id: "ID อำเภอ ต้องเป็นตัวเลข เท่านั้น",
      subdistrict_id: "ID ตำบล ต้องเป็นตัวเลข เท่านั้น",
      zip_code: " รหัสไปรษณีย์ ต้องเป็นตัวเลข เท่านั้น",
    },
  };

  