// app/layout.js
import "@/app/globals.css";
import '@/app/login.css';

import { getSessionServer } from "@/lib/session";
import { date, datetime, times, day, nowMs, nowSec, nowDate } from "@/lib/utils/dateFormat";
import InitialWrapper from "@/components/Initial/InitialWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getSessionServer();

  const sessionData = session ? JSON.parse(JSON.stringify(session)) : null;

  return (
    <html lang="en">
      
      <body
        className={``}
        
      >
        <InitialWrapper sessionData={sessionData} />
        <div className="app-container">
          {children}
        </div>
      </body>
    </html>
  );
}
